name: spam_filter
description: A new Flutter project.



publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  feather_icons: ^1.2.0
  colorize_text_avatar: ^1.0.2
  shimmer: ^2.0.0
  google_nav_bar: ^5.0.6
  flutter_sms_inbox: ^1.0.1
  permission_handler: ^10.0.2
  provider: ^6.0.3
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_contacts: ^1.1.5
  telephony: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # example:
  fonts:
    - family: PassionOne
      fonts:
        - asset: fonts/passion_one/PassionOne-Bold.ttf
          weight: 900
        - asset: fonts/passion_one/PassionOne-Regular.ttf
    
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Regular.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 400
        - asset: fonts/montserrat/Montserrat-Thin.ttf
          weight: 300

    - family: Merriweather
      fonts:
        - asset: fonts/merriweather/Merriweather-Bold.ttf
          weight: 900

    - family: Quicksand
      fonts:
        - asset: fonts/quicksand/Quicksand-Regular.ttf
          weight: 500
        - asset: fonts/quicksand/Quicksand-Bold.ttf
          weight: 900
        


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
